language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  # To see available versions:
  #   s3cmd ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
  - pypy
  - pypy3
dist: xenial

matrix:
  include:
    - os: linux
      language: python
      python: 3.7
      env: OLD_CRYPTOGRAPHY=2.6.1
    - os: linux
      language: python
      python: 3.7
      env: DOC_BUILD=1

script:
  - ci/travis.sh
